name: Node CI Pipeline

on:
  push:
    branches:
      - develop
      - multistage
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ci-cd-demo
      APP_ENV: ${{ vars.APP_ENV }}
      API_URL: ${{ secrets.API_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Print message
      # run: echo "CI is working!"

      # - name: Show Node version
      # run: node -v

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm' # MAGIC LINE

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Check Formatting
        run: npm run format:check

      - name: Run tests
        run: npm test

      # - name: Run app
      # run: npm start

      # - name: List files
      # run: ls -la

      # - name: Build Docker image
      # run: docker build -t ci-cd-demo .

      - name: Set Deployment Variables
        run: |
          if [ "${GITHUB_REF_NAME}" = "develop" ]; then
            echo "PORT=3001" >> $GITHUB_ENV
            echo "CONTAINER_NAME=ci-cd-demo-dev" >> $GITHUB_ENV
            echo "IMAGE_TAG=dev" >> $GITHUB_ENV

          elif [ "${GITHUB_REF_NAME}" = "multistage" ]; then
            echo "PORT=3002" >> $GITHUB_ENV
            echo "CONTAINER_NAME=ci-cd-demo-multistage" >> $GITHUB_ENV
            echo "IMAGE_TAG=multistage" >> $GITHUB_ENV

          else
            echo "PORT=3000" >> $GITHUB_ENV
            echo "CONTAINER_NAME=ci-cd-demo-prod" >> $GITHUB_ENV
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }} .

      - name: Push Image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker pull ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}

            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true

            docker run -d --name ${{ env.CONTAINER_NAME }} --restart unless-stopped -p ${{ env.PORT }}:3000 ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
