name: Node CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print message
        run: echo "CI is working!"

      - name: Show Node version
        run: node -v

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm' # MAGIC LINE

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Check Formatting
        run: npm run format:check

      - name: Run tests
        run: npm testk

      - name: Run app
        run: npm start

      - name: List files
        run: ls -la
